esphome:
  name: 6gang_relay
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio 
  project:
    name: esphome.6Gang30AlatchRelay
    version: "1.0"


esp32:
  board: esp32-s2-saola-1
  variant: ESP32S2
  framework:
    type: esp-idf
    version: recommended

preferences:
  flash_write_interval: 0s

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""
 
# This isthe public location of this yaml file.
dashboard_import:
  package_import_url: github://github.com/EasySensors/6Gang30AmpsLatchRelayEspHomeReady/edit/main/6Gang30AmpsLatchRelay.yaml@main

#esp32_improv:
#  authorizer: false

wifi:
  ssid: ""
  password: ""
  #use_address: "192.168.1.88"


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Cam Fallback Hotspot"
    password: "12345678"

    
#  manual_ip:
#    static_ip: 192.168.1.88
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
# This feature is only available with frameworks ['arduino'].
# captive_portal:  

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
#esp32_improv:
#  authorizer: none

# Sets up the improv via serial client for Wi-Fi provisioning.
# Handy if your device has a usb port for the user to add credentials when they first get it.
improv_serial:

i2c:
  sda: GPIO17
  scl: GPIO18
  scan: true

pcf8574:
  - id: 'pcf8574_hub'
    address: 0x20
    pcf8575: false


interval:
        
  - interval: 5s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - lambda: |- 
              if (!id(wifi_led).state) {
              id(wifi_led).turn_on();
              } 
        else:
          - lambda: |- 
              if (id(wifi_led).state) {
              id(wifi_led).turn_off();
              } 

  - interval: 5s
    then:
      if:
        condition:
          api.connected:
        then:
          - lambda: |- 
              if (!id(api_led).state) {
              id(api_led).turn_on();
              } 
        else:
          - lambda: |- 
              if (id(wifi_led).state) {
              id(wifi_led).turn_off();
              }         

# DS18b20 temperature sensors pins GPIO40 and  GPIO41

# https://esphome.io/components/sensor/dallas.html
# It is highly recommended to use the address attribute for creating 
# dallas sensors, because if you have multiple sensors on a bus and 
# the automatic sensor discovery fails, all sensors indices 
# will be shifted by one. In order to get the address, 
# simply start the firmware on your device with a configured dallas hub 
# and observe the log output (the log level must be set to at least debug!).

dallas:
  - pin: GPIO40
    update_interval: 300s

# Individual sensors  
# Comment out the section below if you need to find out your actual DS18b20 addreses in the log
sensor:
  - platform: dallas
    internal: false
    address: 0x4300000BE7C17F28
    name: "Living Room Temperature"
    filters:
      - filter_out: nan
    

switch:

  - platform: gpio
    name: "wifi LED"
    internal: true
    pin:
      pcf8574: pcf8574_hub
      number: 6
      mode: OUTPUT
      inverted: true
    id: wifi_led
   
  - platform: gpio
    name: "api LED"
    internal: true
    pin:
      pcf8574: pcf8574_hub
      number: 7
      mode: OUTPUT
      inverted: true
    id: api_led


 #-------------------------------------RELAY1 
  - platform: gpio
    pin: GPIO10
    name: "Latch relay 1 ON"
    internal: true
    id: open_switch1

  - platform: gpio
    pin: GPIO9
    name: "Latch relay 1 OFF"
    internal: true
    id: close_switch1

  - platform: gpio
    name: "relay 1 LED"
    internal: true
    pin:
      pcf8574: pcf8574_hub
      number: 0
      mode: OUTPUT
      inverted: true
    id: led1

  - platform: template
    name: "Latch relay switch 1"
    restore_state: true
    id: latch_switch1
    turn_on_action:
      - switch.template.publish:
          id: latch_switch1
          state: ON
      - switch.turn_on: open_switch1
      - delay: 0.1s
      - switch.turn_off: open_switch1
      - logger.log: "turn on action 1"
      - switch.turn_on: led1
    turn_off_action:
      - switch.template.publish:
          id: latch_switch1
          state: OFF
      - switch.turn_on: close_switch1
      - delay: 0.1s
      - switch.turn_off: close_switch1
      - logger.log: "turn off action 1"
      - switch.turn_off: led1

 #-------------------------------------RELAY2 
  - platform: gpio
    pin: GPIO20
    name: "Latch relay 2 ON"
    internal: true
    id: open_switch2

  - platform: gpio
    pin: GPIO3
    name: "Latch relay 2 OFF"
    internal: true
    id: close_switch2

  - platform: gpio
    name: "relay 2 LED"
    internal: true
    pin:
      pcf8574: pcf8574_hub
      number: 1
      mode: OUTPUT
      inverted: true
    id: led2

  - platform: template
    name: "Latch relay switch 2"
    restore_state: true
    id: latch_switch2
    turn_on_action:
      - switch.template.publish:
          id: latch_switch2
          state: ON
      - switch.turn_on: open_switch2
      - delay: 0.1s
      - switch.turn_off: open_switch2
      - logger.log: "turn on action 2"
      - switch.turn_on: led2
    turn_off_action:
      - switch.template.publish:
          id: latch_switch2
          state: OFF
      - switch.turn_on: close_switch2
      - delay: 0.1s
      - switch.turn_off: close_switch2
      - logger.log: "turn off action 2"
      - switch.turn_off: led2

 #-------------------------------------RELAY3
  - platform: gpio
    pin: GPIO19
    name: "Latch relay 3 ON"
    internal: true
    id: open_switch3

  - platform: gpio
    pin: GPIO8
    name: "Latch relay 3 OFF"
    internal: true
    id: close_switch3

  - platform: gpio
    name: "relay 3 LED"
    internal: true
    pin:
      pcf8574: pcf8574_hub
      number: 2
      mode: OUTPUT
      inverted: true
    id: led3

  - platform: template
    name: "Latch relay switch 3"
    restore_state: true
    id: latch_switch3
    turn_on_action:
      - switch.template.publish:
          id: latch_switch3
          state: ON
      - switch.turn_on: open_switch3
      - delay: 0.1s
      - switch.turn_off: open_switch3
      - logger.log: "turn on action 3"
      - switch.turn_on: led3
    turn_off_action:
      - switch.template.publish:
          id: latch_switch3
          state: OFF
      - switch.turn_on: close_switch3
      - delay: 0.1s
      - switch.turn_off: close_switch3
      - logger.log: "turn off action 3"
      - switch.turn_off: led3

 #-------------------------------------RELAY4
  - platform: gpio
    pin: GPIO15
    name: "Latch relay 4 ON"
    internal: true
    id: open_switch4

  - platform: gpio
    pin: GPIO16
    name: "Latch relay 4 OFF"
    internal: true
    id: close_switch4

  - platform: gpio
    name: "relay 4 LED"
    internal: true
    pin:
      pcf8574: pcf8574_hub
      number: 3
      mode: OUTPUT
      inverted: true
    id: led4

  - platform: template
    name: "Latch relay switch 4"
    restore_state: true
    id: latch_switch4
    turn_on_action:
      - switch.template.publish:
          id: latch_switch4
          state: ON
      - switch.turn_on: open_switch4
      - delay: 0.1s
      - switch.turn_off: open_switch4
      - logger.log: "turn on action 4"
      - switch.turn_on: led4
    turn_off_action:
      - switch.template.publish:
          id: latch_switch4
          state: OFF
      - switch.turn_on: close_switch4
      - delay: 0.1s
      - switch.turn_off: close_switch4
      - logger.log: "turn off action 4"
      - switch.turn_off: led4

 #-------------------------------------RELAY5
  - platform: gpio
    pin: GPIO7
    name: "Latch relay 5 ON"
    internal: true
    id: open_switch5

  - platform: gpio
    pin: GPIO6
    name: "Latch relay 5 OFF"
    internal: true
    id: close_switch5

  - platform: gpio
    name: "relay 5 LED"
    internal: true
    pin:
      pcf8574: pcf8574_hub
      number: 4
      mode: OUTPUT
      inverted: true
    id: led5

  - platform: template
    name: "Latch relay switch 5"
    restore_state: true
    id: latch_switch5
    turn_on_action:
      - switch.template.publish:
          id: latch_switch5
          state: ON
      - switch.turn_on: open_switch5
      - delay: 0.1s
      - switch.turn_off: open_switch5
      - logger.log: "turn on action 5"
      - switch.turn_on: led5
    turn_off_action:
      - switch.template.publish:
          id: latch_switch5
          state: OFF
      - switch.turn_on: close_switch5
      - delay: 0.1s
      - switch.turn_off: close_switch5
      - logger.log: "turn off action 5"
      - switch.turn_off: led5

 #-------------------------------------RELAY6
  - platform: gpio
    pin: GPIO5
    name: "Latch relay 6 ON"
    internal: true
    id: open_switch6

  - platform: gpio
    pin: GPIO4
    name: "Latch relay 6 OFF"
    internal: true
    id: close_switch6

  - platform: gpio
    name: "relay 6 LED"
    internal: true
    pin:
      pcf8574: pcf8574_hub
      number: 5
      mode: OUTPUT
      inverted: true
    id: led6

  - platform: template
    name: "Latch relay switch 6"
    restore_state: true
    id: latch_switch6
    turn_on_action:
      - switch.template.publish:
          id: latch_switch6
          state: ON
      - switch.turn_on: open_switch6
      - delay: 0.1s
      - switch.turn_off: open_switch6
      - logger.log: "turn on action 6"
      - switch.turn_on: led6
    turn_off_action:
      - switch.template.publish:
          id: latch_switch6
          state: OFF
      - switch.turn_on: close_switch6
      - delay: 0.1s
      - switch.turn_off: close_switch6
      - logger.log: "turn off action 6"
      - switch.turn_off: led6

#-------------------------------------White cap switches as momentary relay switches

binary_sensor:
  - platform: gpio
    pin: GPIO11
    name: tact_button1
    internal: true
    filters:
      - invert:
      - delayed_on_off: 30ms
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.toggle: latch_switch1

  - platform: gpio
    pin: GPIO12
    name: tact_button2
    internal: true
    filters:
      - invert:
      - delayed_on_off: 30ms
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.toggle: latch_switch2

  - platform: gpio
    pin: GPIO13
    name: tact_button3
    internal: true
    filters:
      - invert:
      - delayed_on_off: 30ms
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.toggle: latch_switch3

  - platform: gpio
    pin: GPIO14
    name: tact_button4
    internal: true
    filters:
      - invert:
      - delayed_on_off: 30ms
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.toggle: latch_switch4

  - platform: gpio
    pin: GPIO21
    name: tact_button5
    internal: true
    filters:
      - invert:
      - delayed_on_off: 30ms
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.toggle: latch_switch5

  - platform: gpio
    pin: GPIO33
    name: tact_button6
    internal: true
    filters:
      - invert:
      - delayed_on_off: 30ms
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.toggle: latch_switch6

#-------------------------------------Optron isolated inputs as toggle switches

  - platform: gpio
    pin: GPIO34
    name: optron_isolated_input1
    internal: true
    filters:
      - invert:
      - delayed_on_off: 30ms
    on_press:
      then:
        - switch.turn_on: latch_switch1
    on_release:
      then:
        - switch.turn_off: latch_switch1

  - platform: gpio
    pin: GPIO35
    name: optron_isolated_input2
    internal: true
    filters:
      - invert:
      - delayed_on_off: 30ms
    on_press:
      then:
        - switch.turn_on: latch_switch2
    on_release:
      then:
        - switch.turn_off: latch_switch2

  - platform: gpio
    pin: GPIO36
    name: optron_isolated_input3
    internal: true
    filters:
      - invert:
      - delayed_on_off: 30ms
    on_press:
      then:
        - switch.turn_on: latch_switch3
    on_release:
      then:
        - switch.turn_off: latch_switch3

  - platform: gpio
    pin: GPIO37
    name: optron_isolated_input4
    internal: true
    filters:
      - invert:
      - delayed_on_off: 30ms
    on_press:
      then:
        - switch.turn_on: latch_switch4
    on_release:
      then:
        - switch.turn_off: latch_switch4

  - platform: gpio
    pin: GPIO38
    name: optron_isolated_input5
    internal: true
    filters:
      - invert:
      - delayed_on_off: 30ms
    on_press:
      then:
        - switch.turn_on: latch_switch5
    on_release:
      then:
        - switch.turn_off: latch_switch5

  - platform: gpio
    pin: GPIO39
    name: optron_isolated_input6
    internal: true
    filters:
      - invert:
      - delayed_on_off: 30ms
    on_press:
      then:
        - switch.turn_on: latch_switch6
    on_release:
      then:
        - switch.turn_off: latch_switch6
