# CHANGEME: Set these variable to your liking
title: 6Gang30AmpsLatchRelayEspHomeReady
description: Powered by ESPHome and ESP Web Tools 6 Gang 30 Ampers Latch Relay In Din-rail enclosure
theme: jekyll-theme-slate
